### ISSUE TITLE
What is the meaning of blank_bias

### ISSUE THREAD

**Issue by cuongducle** [DongjiGao/flexible_alignment#1]
Firstly, thank you for the excellent project. I am also working on integrating the Hugging Face Wav2Vec2 model with WFST for shallow fusion and context biasing. I used K2 to create an HLG graph, but when I decoded it with the Wav2Vec model, the output was weird. Following your advice, I added a blank_score (for me it was 15), and everything went perfectly.

Could you please explain why you added blank_score to your code and why it is set to 0 by default?

Lastly, I want to thank you again because your code helped me solve my problem. I hope you have a good day.

**Comment by DongjiGao** [comment]
> 
Sorry for the late response. 
The blank_bias is inherited from [snowfall](https://github.com/k2-fsa/snowfall/blob/6fe1ff0f7770cc0de580743c48211a1aab9dab5e/egs/librispeech/asr/simple_v1/ctc_decode.py#L62) and is commonly set as a negative value to make the distribution less peaky.
